name: link_tailor 
description: A new Gazelle project.
version: 0.1.0

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  crypto: 3.0.3
  dotenv: 4.2.0
  gazelle_core: 0.3.0
  get_it: 7.7.0
  injectable: 2.4.1
  json_annotation: 4.9.0
  json_serializable: 6.8.0
  logger: 2.3.0
  meta: 1.11.0
  orm: 4.4.0

dev_dependencies:
  build_runner: 2.4.10
  injectable_generator: 2.6.1
  test: 1.25.2
  very_good_analysis: 6.0.0

gazelle:
